# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=500)),
                ("author", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="Badiiy", max_length=100)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="covers/")),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="pdfs/")),
                ("pages", models.PositiveIntegerField(default=0)),
                ("published_year", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
